### ISSUE TITLE
The REST API should accept text

### ISSUE THREAD

**Issue by DavidNemeskey** [dlt-rilmta/xtsv#1]
Currently it is only possible to send an existing input file to the REST API. It would be useful if one could simply send regular text directly in the POST request.

**Comment by dlazesz** [comment]
This is not very well documented, but as file argumetns in HTTP POST can be anything that is an iterator over text chunks (eg. lines in a file) the very same API can be used by turning the input text into an interator:

```python
input_iterator = iter(['Raw text', 'line-by-line'])
r = requests.post('http://127.0.0.1:5000/tok/morph/pos', files={'file': input_iterator})
```

Do you have arguments against this usage in favour of #2?
(It corresponds with the other API-s which also accepts iterators only (eg. STDIN).)

At first glance #2 would duplicate the API with the same purpose and encourage users to use that version over files on large inputs, which are undesirable. However, I can see your motivaton.
If I accept your solution, it will have to cover all three API-s in a sound way.

**Comment by DavidNemeskey** [comment]
One use-case is when I know the document structure, and I want to pass it to the server e.g. paragraph-by-paragraph (so that this information is not lost).

You might be right that if the request accepts everything, such a `StringIO`, this is not necessary _per se_. On the other hand, I think it makes the code cleaner on the client side.

**Comment by dlazesz** [comment]
> One use-case is when I know the document structure, and I want to pass it to the server e.g. paragraph-by-paragraph (so that this information is not lost).

One way to achieve this is when enabling CoNLL-U style comments and mark the paragraph boundaries with special comments.
Or using double empty lines in TSV to mark paragraph boundaries. It triggers warings, but is allowed. 

However, this has nothing to do with the REST API.

> On the other hand, I think it makes the code cleaner on the client side.

This two lines on client side you are talking about:

```python
def query_text(server_url, text):
    return requests.post(server_url, files={'file': iter([text])}).text
```

compared to changing all three API-s on the xtsv side. Not to mention the mutual exclusive nature of `file` and `text` properties.

It does not convince me in the first place.

**Comment by DavidNemeskey** [comment]
How do you put conll-style comments in the original text file? Your suggestions are great once you have a TSV, but usually you start off with raw text.

BTW. which 3 APIs are you talking about on the xtsv side?

**Comment by dlazesz** [comment]
I doubt any tokenizer out there which can handle a custom separator for user defined paragraphs.

The 3 API-s of XTSV are the following:

- The CLI API, that must consist of an [Argparse object](https://github.com/dlt-rilmta/xtsv/blob/master/argparser.py).
- The REST API, that must be a [HTTP POST /tool1/tool2/tool3  URL with file input](https://github.com/dlt-rilmta/xtsv/blob/master/pipeline.py#L167), or [GET tool/text_urlencoded](https://github.com/dlt-rilmta/xtsv/blob/master/pipeline.py#L142)
- The Python API, that is [a set of public functions shared between the three usecases](https://github.com/dlt-rilmta/xtsv/blob/master/__init__.py)

These three API-s must provide the same possibilites in the same or similar way. If you want to extend any of them you must extend all of them properly.

**I have an idea for you**: If your input data is rather small < 8KB we could extend the usecase of the HTTP GET to handle direct text input for multiple tools an more than one tokens [as long as the servers between tolerates it](https://stackoverflow.com/questions/2659952/maximum-length-of-http-get-request/2659995#2659995).  This would overcome the problem of handling two mutualy exclusive usecases for POST, that you proposed and could be implemented for all three API-s easily. **Does it fit your requirements?**

**Comment by dlazesz** [comment]
- Implemeneted in ff422afc64cf39c9c5dcaa813e0f653d61c7034c
- See documentation https://github.com/dlt-rilmta/xtsv#rest-api

Thank you for your suggestion.
