### ISSUE TITLE
CoNLL comments

### ISSUE THREAD

**Issue by DavidNemeskey** [dlt-rilmta/xtsv#3]
CoNNL-U supports comments, i.e. lines that precede a sentence and start with a hash mark (`#`). However, it is possible for a sentence to start with a hash mark, or (since Twitter) a hashtag. These sentences are not handled correctly by xtsv.

I propose that only those lines are handled as comments that start with a hash mark AND a space. This issue does not affect the regular CoNLL-U format, as there the first column is the node ID; but since emtsv does not add the node ID column, this problem can happen.

**Comment by dlazesz** [comment]
Implemented in 7dcb1d2

Thank you for your suggestion.
